[package]
name = "optional_struct"
version = "0.1.0"
authors = ["Paul Lesur <paul.lesur@plesur.fr>"]
description = "Crate defining a macro that will generate, from a structure, another structure with only Option<T> fields"
readme = "README.md"
categories = ["config"]
license = "Apache-2.0"

[dependencies]
syn = "0.11.11"
quote = "0.3"

[lib]
proc-macro = true


